name: Build and Push Docker Image

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Buildx the Docker image
      uses: docker/setup-buildx-action@v2

    - name: Logs in to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Convert uppercase to lowercase
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          
    - name: Pushes the Docker image to the registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:latests